[build]
  base = "Frontend"
  command = "npm install && npm run build -- --configuration production"
  publish = "dist/Frontend/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
